name: ArianeServer CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '15'
      - name: Build with Gradle
        run: ./gradlew :server:build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '15'
      - name: Run server tests
        run: ./gradlew :server:test

  deploy-graphql-ktx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '15'
      - name: Prepare environment
        env:
          GRADLE_PROPERTIES: ${{secrets.GRADLE_PROPERTIES}}
          GRADLE_PROPERTIESTOTO: ${{secrets.GRADLE_PROPERTIESTOTO}}
        shell: bash
        run: 'echo "$GRADLE_PROPERTIES" > gradle.properties'
      - name: Deploy GraphQL-ktx library
        run: ./gradlew :graphql-ktx:publishToSonatype