name: ArianeServer CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup submodules
        run: git submodule init && git submodule update
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew :server:build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup submodules
        run: git submodule init && git submodule update
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Run server tests
        run: ./gradlew :server:test

  deploy-server:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup submodules
        run: git submodule init && git submodule update
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Prepare environment
        env:
          GRADLE_PROPERTIES: ${{secrets.GRADLE_PROPERTIES}}
        shell: bash
        run: 'echo "$GRADLE_PROPERTIES" > gradle.properties'
      - name: Deploy server library
        run: cd server/ && ../gradlew :server:publishToSonatype

  deploy-server-ktor:
    needs: deploy-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup submodules
        run: git submodule init && git submodule update
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Prepare environment
        env:
          GRADLE_PROPERTIES: ${{secrets.GRADLE_PROPERTIES}}
        shell: bash
        run: 'echo "$GRADLE_PROPERTIES" > gradle.properties'
      - name: Deploy Server Ktor library
        run: cd server-ktor/ && ../gradlew :server-ktor:publishToSonatype

  deploy-codegen-plugin:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup submodules
        run: git submodule init && git submodule update
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Prepare environment
        env:
          GRADLE_PROPERTIES: ${{secrets.GRADLE_PROPERTIES}}
        shell: bash
        run: 'echo "$GRADLE_PROPERTIES" > gradle.properties && cat gradle.properties | tr SONATYPE_USERNAME foo_bar'
      - name: Deploy codegen plugin
        run: cd server/ && ../gradlew :codegen:publishPluginMavenPublicationToSonatypeRepository